CREATE TABLE IF NOT EXISTS site_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(64) NOT NULL UNIQUE,
  payload LONGTEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS diagnostic_submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_path VARCHAR(512) NOT NULL,
  severity VARCHAR(32) DEFAULT NULL,
  issue_type VARCHAR(255) DEFAULT NULL,
  analysis TEXT DEFAULT NULL,
  is_ambiguous TINYINT(1) DEFAULT 0,
  client_ip VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(64) NOT NULL,
  locality VARCHAR(255) DEFAULT NULL,
  source VARCHAR(64) NOT NULL,
  metadata JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
